# Generated by Django 5.2.4 on 2025-07-22 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0007_alter_technicalskill_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='achievements',
        ),
    ]
