# Generated by Django 5.2.4 on 2025-07-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0008_remove_workexperience_achievements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='technologies',
        ),
        migrations.AddField(
            model_name='workexperience',
            name='technologies',
            field=models.TextField(blank=True),
        ),
    ]
